In [115]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [116]:
df = pd.read_csv('/home/atiar/Videos/data analysis/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [117]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [118]:
for col in ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']:
    median_value = df[col].median()
    df[col]=df[col].replace(0,median_value)
    

In [119]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35     30.5  33.6   
1            1       85             66             29     30.5  26.6   
2            8      183             64             23     30.5  23.3   
3            1       89             66             23     94.0  28.1   
4            3      137             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [120]:
max_glucose = df['Glucose'].max()
max_glucose

199

In [121]:
df.at[0,'Glucose']=max_glucose
df.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      199             72             35     30.5  33.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1

In [122]:
min_age = df.Age.min()
min_age

21

In [123]:
min_glucose = df.Glucose.min()
min_glucose

44

In [124]:
df.loc[df['Age']==min_age,'Glucose'] = max_glucose
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      199             72             35     30.5  33.6   
1            1       85             66             29     30.5  26.6   
2            8      183             64             23     30.5  23.3   
3            1      199             66             23     94.0  28.1   
4            3      137             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [125]:
#import sklearn model use for linearRegression and all score

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,recall_score,precision_score,confusion_matrix,f1_score
from sklearn.model_selection import train_test_split

In [126]:
x=df.drop(columns='Outcome')

In [127]:
y=df['Outcome']

In [128]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [129]:
reg_model = LinearRegression()

In [130]:
reg_model.fit(x_train,y_train)

LinearRegression()

In [131]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [132]:
y_pred = reg_model.predict(x_test)
y_pred

array([ 0.4557361 ,  0.12051372,  0.1309465 ,  0.16396328,  0.25741052,
        0.3069807 ,  0.33102332, -0.01407965,  0.20203618,  0.31483778,
        0.41756143,  0.08522196,  1.13991578,  0.73247425,  0.63816585,
        0.58376243,  0.26518565,  0.32298494, -0.10149949,  0.23612774,
        0.43944055,  0.25901248,  1.05672577,  0.33836014,  0.03610312,
        0.40967528,  0.2740288 ,  0.57039118,  0.16602619,  0.37041659,
        0.63903337,  0.21472563, -0.02529714,  0.64306733,  0.19516981,
        0.60558665,  0.07457232,  0.23158322,  0.26784708,  0.68338387,
        0.33528788,  0.11363113, -0.0215953 ,  0.32408857,  0.01153849,
        0.1504409 ,  0.60375568,  0.46846304,  0.07265883,  0.1783907 ,
       -0.0057336 ,  0.25566504,  0.65058398, -0.07084778,  0.8258661 ,
        0.13321944,  0.27192307,  0.41655055,  0.62560442,  0.30880482,
        0.6423823 ,  0.39695451,  0.7208726 ,  0.26072894,  0.52312253,
        0.06261081,  0.46924044,  0.43859362,  0.65634645,  0.62

In [133]:
y_pred_round = y_pred.round()
y_pred_round

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  0.,  0., -0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0., -0.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0., -0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -0.,  0.,
        1., -0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  1.,  1.,  1.,  1.,  1., -0.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
       -0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.])

In [134]:
accuracy = accuracy_score(y_test,y_pred_round)
accuracy

0.7597402597402597

In [135]:
con_matrix = confusion_matrix(y_test,y_pred_round)
con_matrix

array([[86, 13],
       [24, 31]])

In [136]:
precision = precision_score(y_test,y_pred_round)
precision

0.7045454545454546

In [137]:
recall = recall_score(y_test,y_pred_round)
recall

0.5636363636363636

In [138]:
f1 = f1_score(y_test,y_pred_round)
f1

0.6262626262626263

In [139]:
from sklearn.metrics import mean_squared_error
score = mean_squared_error(y_test,y_pred_round)
score

0.24025974025974026